-- MySQL Script generated by MySQL Workbench
-- Fri May 31 15:18:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hzq_wiki
-- -----------------------------------------------------
-- Wiki管理系统数据库

-- -----------------------------------------------------
-- Schema hzq_wiki
--
-- Wiki管理系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hzq_wiki` DEFAULT CHARACTER SET utf8 ;
USE `hzq_wiki` ;

-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_doc_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_doc_content` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_doc_content` (
  `id` INT(10) NOT NULL,
  `doc_id` INT(10) NULL COMMENT '文档id',
  `parent_id` INT(10) NULL COMMENT '父级别id',
  `version` VARCHAR(45) NULL COMMENT '版本号,默认是latest 版本规则	年月日小时分钟秒/2019.04.16.16.23.23',
  `title` VARCHAR(125) NULL COMMENT '标题',
  `content` TEXT NULL COMMENT '内容 mk格式',
  `cotent_html` TEXT NULL COMMENT '文档内容 html格式',
  `sequence` INT(10) NULL COMMENT '排序',
  `create_by` INT(10) NULL,
  `create_time` DATETIME NULL,
  `update_by` INT(10) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '文档内容';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
