-- MySQL Script generated by MySQL Workbench
-- Mon May 20 09:46:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hzq_wiki
-- -----------------------------------------------------
-- Wiki管理系统数据库

-- -----------------------------------------------------
-- Schema hzq_wiki
--
-- Wiki管理系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hzq_wiki` DEFAULT CHARACTER SET utf8 ;
USE `hzq_wiki` ;

-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_user` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '用户名称',
  `username` VARCHAR(45) NULL COMMENT '登陆名称',
  `password` VARCHAR(255) NULL COMMENT '登陆密码',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `phone` VARCHAR(16) NULL COMMENT '手机号码',
  `remark` VARCHAR(255) NULL COMMENT '备注说明',
  `create_by` INT(10) NULL,
  `create_time` DATETIME NULL,
  `update_by` INT(10) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
