-- MySQL Script generated by MySQL Workbench
-- Fri May 17 09:29:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hzq_wiki
-- -----------------------------------------------------
-- Wiki管理系统数据库

-- -----------------------------------------------------
-- Schema hzq_wiki
--
-- Wiki管理系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hzq_wiki` DEFAULT CHARACTER SET utf8 ;
USE `hzq_wiki` ;

-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_space`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_space` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_space` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL COMMENT '空间名称',
  `desc` VARCHAR(255) NULL COMMENT '描述',
  `visit_level` TINYINT(1) NULL DEFAULT 1 COMMENT '访问级别 0 私有的 1 公开的',
  `create_by` INT(10) NULL,
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_by` INT(10) NULL COMMENT '更新人id',
  `update_time` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '空间表';


-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_user` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_user` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '用户名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_user_space`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_user_space` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_user_space` (
  `id` INT(10) NOT NULL,
  `user_id` INT(10) NULL,
  `space_id` INT(10) NULL,
  `privilege` TINYINT(1) NULL DEFAULT 0 COMMENT '空间成员操作权限 0 浏览者 1 编辑者 2 管理员',
  `create_by` INT(10) NULL,
  `create_time` DATETIME NULL,
  `update_by` INT(10) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户跟空间的关系表';


-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_doc` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_doc` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL COMMENT '文档名称',
  `space_id` INT(10) NULL COMMENT '项目空间外键',
  `desc` VARCHAR(255) NULL COMMENT '项目描述',
  `visit_level` TINYINT(1) NULL COMMENT '访问级别 0 私有的 1 公开的',
  `img` VARCHAR(255) NULL COMMENT '项目图片',
  `create_by` INT(10) NULL,
  `create_time` DATETIME NULL,
  `update_by` INT(10) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '文档表';


-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_doc_catalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_doc_catalog` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_doc_catalog` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `doc_id` INT(10) NULL COMMENT '文档id',
  `parent_id` INT(10) NULL COMMENT '上级id',
  `name` VARCHAR(45) NULL COMMENT '目录名称',
  `sequence` INT(10) NULL COMMENT '排序 (从小到大)',
  `create_by` INT(10) NULL,
  `create_time` DATETIME NULL,
  `update_by` INT(10) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '文档目录';


-- -----------------------------------------------------
-- Table `hzq_wiki`.`hw_doc_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_wiki`.`hw_doc_content` ;

CREATE TABLE IF NOT EXISTS `hzq_wiki`.`hw_doc_content` (
  `id` INT(10) NOT NULL,
  `doc_id` INT(10) NULL COMMENT '文档id',
  `cata_id` INT(10) NULL COMMENT '目录id,文章标题id',
  `version` VARCHAR(45) NULL COMMENT '版本号,默认是latest 版本规则	年月日小时分钟秒/2019.04.16.16.23.23',
  `content` TEXT NULL COMMENT '内容',
  `create_by` INT(10) NULL,
  `create_time` DATETIME NULL,
  `update_by` INT(10) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '文档内容';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
